spring.datasource.url=jdbc:mysql://localhost:3306/spvms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@Joshi#2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Email Configuration (Sprint-4)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joshiumang311@gmail.com
spring.mail.password=lqss tjar edkk tyoq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
